AWSTemplateFormatVersion: 2010-09-09
Description: 'A CloudFormation template to form a VPC for our tutorial'
#Parameters:
#  OwnerName:
#    Description: 'The name of the owning engineer for the item'
#    Type: String
#    Default: 'Ernie Van Duyne'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/19
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: EVD-QA-VPC--CF
  DMZSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref VPC
      CidrBlock: 192.168.0.0/23
      Tags:
        - Key: Name
          Value: QA DMZ Subnet AZ-1a--CF
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref VPC
      CidrBlock: 192.168.2.0/23
      Tags:
        - Key: Name
          Value: QA DMZ Subnet AZ-1b--CF
  PublicSubnet1a:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1a
        VpcId: !Ref VPC
        CidrBlock: 192.168.4.0/23
        Tags:
          - Key: Name
            Value: QA Public Subnet AZ-1a--CF
  PublicSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref VPC
      CidrBlock: 192.168.6.0/23
      Tags:
        - Key: Name
          Value: QA Public Subnet AZ-1b--CF
  PrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref VPC
      CidrBlock: 192.168.8.0/23
      Tags:
        - Key: Name
          Value: QA Private Subnet AZ-1a--CF
  PrivateSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref VPC
      CidrBlock: 192.168.10.0/23
      Tags:
        - Key: Name
          Value: QA Private Subnet AZ-1b--CF
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: QA-Internet-Gateway--CF
  VPCGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref VPC
        InternetGatewayId: !Ref InternetGateway
  MainRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: QA-RoutingTable--CF